-- Get column names from ftr_transaction
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'FTR_TRANSACTION'
  AND COLUMN_NAME ILIKE '%CARD%'
ORDER BY ORDINAL_POSITION;
